.TH "include Directory Reference" 3 "Sat Dec 1 2018" "Version v0.0.1" "Minimal Scheme/Lisp Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBchars\&.h\fP"
.br
.RI "definitions of functions to handle string "
.ti -1c
.RI "file \fBeval\&.h\fP"
.br
.RI "declaration of evaluation-related functions "
.ti -1c
.RI "file \fBgc\&.h\fP"
.br
.ti -1c
.RI "file \fBlexer\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.h\fP"
.br
.RI "definition of debugging symbols and error types "
.ti -1c
.RI "file \fBnative\&.h\fP"
.br
.ti -1c
.RI "file \fBpair\&.h\fP"
.br
.ti -1c
.RI "file \fBparser\&.h\fP"
.br
.ti -1c
.RI "file \fBrepl\&.h\fP"
.br
.ti -1c
.RI "file \fBscope\&.h\fP"
.br
.ti -1c
.RI "file \fBsexpr\&.h\fP"
.br
.RI "definitions of s-expression and its types, lambda "
.ti -1c
.RI "file \fBtoken\&.h\fP"
.br
.RI "definition of functionalities to handle tokens and their types "
.ti -1c
.RI "file \fBtypes\&.h\fP"
.br
.RI "contains all types used in the project "
.ti -1c
.RI "file \fBvector\&.h\fP"
.br
.RI "definition of Vector Data Structure functionalities "
.in -1c
