.TH "GC_INFO" 3 "Sat Dec 1 2018" "Version v0.0.1" "Minimal Scheme/Lisp Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GC_INFO \- information about the garbage collection  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gc\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBismarked\fP"
.br
.RI "is marked as reachable! "
.ti -1c
.RI "bool \fBisglobal\fP"
.br
.RI "is it defined in the global scope "
.ti -1c
.RI "bool \fBispinned\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
information about the garbage collection 
.SH "Field Documentation"
.PP 
.SS "bool isglobal"

.PP
is it defined in the global scope 
.SS "bool ismarked"

.PP
is marked as reachable! 
.SS "bool ispinned"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minimal Scheme/Lisp Interpreter from the source code\&.
