.TH "include/repl.h" 3 "Mon Nov 19 2018" "Version v0.0.1" "Minimal Scheme/Lisp Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/repl.h
.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br
\fC#include 'gc\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBREPL_PROMPT\fP   '>'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBrepl\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define REPL_PROMPT   '>'"

.SH "Function Documentation"
.PP 
.SS "void repl (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minimal Scheme/Lisp Interpreter from the source code\&.
