.TH "todo" 3 "Sat Dec 1 2018" "Version v0.0.1" "Minimal Scheme/Lisp Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todoTodo List 
 \- 
.IP "\fBGlobal \fBERR_MDFY_RSRVD\fP \fP" 1c
include constants too (after finding the correct syntax)  
.IP "\fBFile \fBgc\&.c\fP \fP" 1c
figure out how to eliminate code-redundancy
.PP
find where do pinned sexprs go while recursion  
.IP "\fBFile \fBscope\&.c\fP \fP" 1c
find a way to remap multiple symbols to the same value, much like pointers  
.IP "\fBGlobal \fBSCOPE_BOND::isconst\fP \fP" 1c
implement this 
.PP

