.TH "src/tst.c" 3 "Mon Nov 19 2018" "Version v0.0.1" "Minimal Scheme/Lisp Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tst.c
.SH SYNOPSIS
.br
.PP
\fC#include 'vector\&.h'\fP
.br
\fC#include 'lexer\&.h'\fP
.br
\fC#include 'parser\&.h'\fP
.br
\fC#include 'eval\&.h'\fP
.br
\fC#include 'scope\&.h'\fP
.br
\fC#include 'repl\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdebug_int\fP (FILE *stream, \fBobject_t\fP o)"
.br
.ti -1c
.RI "void \fBprint_int\fP (\fBobject_t\fP o)"
.br
.ti -1c
.RI "void \fBfree_int\fP (\fBobject_t\fP o)"
.br
.ti -1c
.RI "void \fBvector_testing\fP (void)"
.br
.ti -1c
.RI "void \fBlexer_testing\fP (void)"
.br
.ti -1c
.RI "void \fBparser_testing\fP (void)"
.br
.ti -1c
.RI "void \fBeval_testing\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void debug_int (FILE * stream, \fBobject_t\fP o)"

.SS "void eval_testing ()"

.SS "void free_int (\fBobject_t\fP o)"

.SS "void lexer_testing (void)"

.SS "void parser_testing (void)"

.SS "void print_int (\fBobject_t\fP o)"

.SS "void vector_testing (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minimal Scheme/Lisp Interpreter from the source code\&.
